config/routes.rb
GarbageCollector::Application.routes.draw do
  
  resources :donations

  resources :collection_points

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)

  resources :bonus, only: [:index]

  resources :abouts, only: [:index]

  resources :contacts, only: [:new, :create]

  devise_for :users,  controllers: { registrations: "users/registrations",  
  	omniauth_callbacks: "users/omniauth_callbacks" }
  
  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
	  user ||= User.new
	  if user.role? "Manager"
	  	can :manage, :all
	  end
	end    
end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bonu.rb
class Bonu < ActiveRecord::Base
	has_many :donations
end

app/models/collection_point.rb
class CollectionPoint < ActiveRecord::Base
  belongs_to :user
  has_many :donations
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :user
  belongs_to :collection_point
  belongs_to :bonu
end

app/models/role.rb
class Role < ActiveRecord::Base

	has_many :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates_presence_of :name, message: "Campo Obrigatório"

  scope :rank, -> { order(points: :desc) }

  belongs_to :role
  has_many :collection_points
  has_many :donations

  def get_name
  	self.name.upcase
  end

  def role?(r)
    self.role.name == r
  end

  def donate(device)
    self.points += device[:points]
  end

  def self.from_omniauth(auth)
  	where(auth.slice(:provider, :uid)).first_or_create do |user|
  		user.provider = auth.provider
  		user.uid = auth.uid
			user.email = auth.info.email 
      user.name = auth.info.name
  	end
  end

  def self.new_with_session(params, session)
  	if session["devise.user_attributes"]
  		new(session["devise.user_attributes"], without_protection: true) do |user|
  			user.attributes = params
  			user.valid?
  		end
  	else
  		super
  	end
  end

  def password_required?
  	super && provider.blank?
  end

  def update_with_password(params, *options)
  	if encrypted_password.blank?
  		update_attributes(params, *options)
  	else
  		super
  	end
  end

end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

  def index
    @abouts = About.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    flash[:danger] = exception.message
    render :file => "#{Rails.root}/public/403.html", :status => 403, :layout => false
  end

  before_filter do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end
end

app/controllers/bonus_controller.rb
class BonusController < ApplicationController

  def index
    @bonus = Bonu.all
  end
 
end

app/controllers/collection_points_controller.rb
class CollectionPointsController < InheritedResources::Base

	def index
		@collection_points = current_user.collection_points.all
	end

	def create
		@collection_point = CollectionPoint.new(collection_point_params)
		@collection_point.user = current_user
		respond_to do |format|
			if @collection_point.save
				format.html {redirect_to root_path, notice: 'collection_point was successfully created.' }
			else
				respond_with(@collection_point)
			end
		end
	end

	private

	def collection_point_params
		params.require(:collection_point).permit(:user_id, :address, :name, :google_address, :complement)
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  respond_to :html, :xml, :json
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def new
    @contact = Contact.new
    respond_with(@contact)
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)
    respond_to do |format|
      if @contact.save
        ContactMailer.contact_data(@contact).deliver!
        ContactMailer.thanks(@contact).deliver!
        format.html {redirect_to root_path, notice: 'Contact was successfully created.' }
      else
        respond_with(@contact)
      end
    end
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:full_name, :email, :subject, :body)
    end
end

app/controllers/donations_controller.rb
class DonationsController < InheritedResources::Base

  private

    def donation_params
      params.require(:donation).permit(:user_id, :collection_point_id, :bonu_id, :pending, :points)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bonus_helper.rb
module BonusHelper
end

app/helpers/collection_points_helper.rb
module CollectionPointsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/abouts/index.html.erb
<div class="container">
  <br>
  <div>
    <% @abouts.each do |about| %>

    <div class="col-md-offset-3 col-md-6 col-md-offset-3">
      <h1>Nosso trabalho</h1>
      <hr class="linha">
      <div align="center"><%= image_tag("logolixo.jpg", size:'430x180')%></div>
      <br>
      <hr class="linha"> 
      <div id="justificandotexto"><%= raw about.body %></div>
      
    </div>

    
    <% end %>
  </div>



  <br>

  <% if @abouts.empty? %>
  <%= link_to 'New About', new_about_path %>
  <% end %>

</div>

app/views/bonus/index.html.erb
<div class="container">
  <div class="page-header">
    <h1>Lista de Pontos</h1>
  </div>

  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">Pontos</h3>
    </div>
    <div class="panel-body">
      <table class="table">
        <thead>
          <tr class="text-primary">
            <th>Lixo</th>
            <th>Pontos</th>
          </tr>
        </thead>

        <tbody>
          <% @bonus.each do |bonu| %>
            <tr class="text-info">
              <td><%= bonu.name %> pts</td>
              <td><%= bonu.points %> pts</td>
            </tr>
          <% end %>
        </tbody>
      </table>      
    </div>
  </div>
</div>

<br>
  <br>
  <br>
  <br>
  

app/views/collection_points/_form.html.erb
<%= simple_form_for(@collection_point) do |f| %>
  <%= f.error_notification %>

  <div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Course</h3>
      </div>
      
      <div class="panel-body">
        <div class="form-inputs">
          <%= f.input :address, label: "Endereço" %>
          <%= f.input :name, label: "Nome" %>
          <%= f.input :google_address %>
          <%= f.input :complement, label: "Complemento" %>
        </div>

        <div class="form-actions">
          <%= f.submit "Cadastrar", class: "btn btn-default" %>
        </div>
      
      </div>
    </div>
<% end %>

app/views/collection_points/edit.html.erb
<h1>Editing collection_point</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection_point %> |
<%= link_to 'Back', collection_points_path %>

app/views/collection_points/index.html.erb
<div class="container">
  <div class="page-header">
    <h1>Listando Pontos de Coleta</h1>
  </div>

  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">Pontos</h3>
    </div>
    <div class="panel-body">
      <table class="table">
        <thead>
          <tr>
            <th>Address</th>
            <th>Name</th>
            <th>Google address</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @collection_points.each do |collection_point| %>
          <tr>
           <td><%= collection_point.address %></td>
           <td><%= collection_point.name %></td>
           <td><%= collection_point.google_address %></td>
           <td><%= link_to 'Exibir', collection_point %></td>
           <td><%= link_to 'Editar', edit_collection_point_path(collection_point) %></td>
           <td><%= link_to 'Deletar', collection_point, method: :delete, data: { confirm: 'Você tem certeza disso?' } %></td>
         </tr>
         <% end %>
       </tbody>
     </table>      
   </div>
 </div>

 <%= link_to 'Novo Ponto de Coleta', new_collection_point_path, class: "btn btn-info" %>

 <br>
</div>

app/views/collection_points/new.html.erb
<div class="container">
	<div class="page-header">
		<h1>Novo Ponto de Coleta</h1>
	</div>

	<%= render 'form' %>
</div>

app/views/collection_points/show.html.erb
<div class="container" style="margin-top: 50px">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h2 class="panel-title">Ponto</h2>
    </div>
    <div class="panel-body">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Nome:</strong>
        <%= @collection_point.name %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= @collection_point.address %>
      </p>


      <p>
        <strong>Google address:</strong>
        <%= @collection_point.google_address %>
      </p>

      <p>
        <strong>Complement:</strong>
        <%= @collection_point.complement %>
      </p>
    </div>
  </div>

  <%= link_to 'Editar', edit_collection_point_path(@collection_point) %> |
  <%= link_to 'Voltar', collection_points_path %>
</div>
  

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :full_name, label: false, placeholder: "NOME COMPLETO" %>
    <%= f.input :email, label: false, placeholder: "E-MAIL" %>
    <%= f.input :subject, label: false, placeholder: "ASSUNTO" %>
    <%= f.input :body, label: false, placeholder: "MENSAGEM" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "col-md-12" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/new.html.erb
<div class="jumbotron jumbotron-sm corfundocontato">
	<div class="container">
		<div class="row">
			<div class="com-sm-12 col-lg-12">
				<h1 class="h1">
					Entre em contanto conosco <small id="fontepreta">Tire suas dúvidas</small>
				</h1>
			</div>
		</div>
	</div>
</div>

<section class="col-md-12" id="margem">
	<div class="col-md-offset-4 col-md-4 col-md-offset-4">
	<br>
	<br>
	
		<%= render 'form' %>
	<br>
	<br>
	<br>
	<br>	
	</div>
</section>

app/views/donations/_form.html.erb
<%= simple_form_for(@donation) do |f| %>
  <%= f.error_notification %>

  <div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Doação</h3>
      </div>
      
      <div class="panel-body">

        <div class="form-inputs">
          <%= f.association :collection_point, label: "Ponto de Coleta" %>
          <%= f.association :bonu, label: "Dispositivo" %>
        </div>

        <div class="form-actions">
          <%= f.submit "Doar", class: "btn btn-info" %>
        </div>

      </div>

    </div>
<% end %>

app/views/donations/edit.html.erb
<div class="container">
	<div class="page-header">
		<h1>Editar Doação</h1>
	</div>

	<%= render 'form' %>
</div>

app/views/donations/index.html.erb
<h1>Listing donations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Collection point</th>
      <th>Bonu</th>
      <th>Pending</th>
      <th>Points</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.user %></td>
        <td><%= donation.collection_point %></td>
        <td><%= donation.bonu %></td>
        <td><%= donation.pending %></td>
        <td><%= donation.points %></td>
        <td><%= link_to 'Show', donation %></td>
        <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
        <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<div class="container">
	<div class="page-header">
		<h1>Nova Doação</h1>
	</div>

	<%= render 'form' %>
</div>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @donation.user %>
</p>

<p>
  <strong>Collection point:</strong>
  <%= @donation.collection_point %>
</p>

<p>
  <strong>Bonu:</strong>
  <%= @donation.bonu %>
</p>

<p>
  <strong>Pending:</strong>
  <%= @donation.pending %>
</p>

<p>
  <strong>Points:</strong>
  <%= @donation.points %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>