config/routes.rb
GarbageCollector::Application.routes.draw do
  
  resources :donations

  resources :collection_points

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)

  resources :bonus, only: [:index]

  resources :abouts, only: [:index]

  resources :contacts, only: [:new, :create]

  devise_for :users,  controllers: { registrations: "users/registrations",  
  	omniauth_callbacks: "users/omniauth_callbacks" }
  
  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
	  user ||= User.new
	  if user.role? "Manager"
	  	can :manage, :all
	  end
	end    
end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bonu.rb
class Bonu < ActiveRecord::Base
	has_many :donations
end

app/models/collection_point.rb
class CollectionPoint < ActiveRecord::Base
  belongs_to :user
  has_many :donations
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :user
  belongs_to :collection_point
  belongs_to :bonu
end

app/models/role.rb
class Role < ActiveRecord::Base

	has_many :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates_presence_of :name, message: "Campo Obrigatório"

  scope :rank, -> { order(points: :desc) }

  belongs_to :role
  has_many :collection_points
  has_many :donations

  def get_name
  	self.name.upcase
  end

  def role?(r)
    self.role.name == r
  end

  def donate(device)
    self.points += device[:points]
  end

  def self.from_omniauth(auth)
  	where(auth.slice(:provider, :uid)).first_or_create do |user|
  		user.provider = auth.provider
  		user.uid = auth.uid
			user.email = auth.info.email 
      user.name = auth.info.name
  	end
  end

  def self.new_with_session(params, session)
  	if session["devise.user_attributes"]
  		new(session["devise.user_attributes"], without_protection: true) do |user|
  			user.attributes = params
  			user.valid?
  		end
  	else
  		super
  	end
  end

  def password_required?
  	super && provider.blank?
  end

  def update_with_password(params, *options)
  	if encrypted_password.blank?
  		update_attributes(params, *options)
  	else
  		super
  	end
  end

end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

  def index
    @abouts = About.all
  end

end

app/controllers/bonus_controller.rb
class BonusController < ApplicationController

  def index
    @bonus = Bonu.all
  end
 
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  respond_to :html, :xml, :json
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def new
    @contact = Contact.new
    respond_with(@contact)
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)
    respond_to do |format|
      if @contact.save
        ContactMailer.contact_data(@contact).deliver!
        ContactMailer.thanks(@contact).deliver!
        format.html {redirect_to root_path, notice: 'Contact was successfully created.' }
      else
        respond_with(@contact)
      end
    end
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:full_name, :email, :subject, :body)
    end
end

app/controllers/donations_controller.rb
class DonationsController < InheritedResources::Base

  private

    def donation_params
      params.require(:donation).permit(:user_id, :collection_point_id, :bonu_id, :pending, :points)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bonus_helper.rb
module BonusHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_logged_user.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= icon('user', current_user.get_name) %></a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to icon('edit', 'Meu Perfil'), edit_user_registration_path(current_user) %>
    </li>
    <li>
      <%= link_to icon('gamepad', 'Meus Pontos'), root_path %>
    </li>
    <% if current_user.role?("Collector") %>
      <li>
        <%= link_to icon('recycle', 'Meus Pontos de Coleta'), collection_points_path %>
      </li>
      <li>
          <%= link_to icon('recycle', 'Novo Ponto de Coleta'), new_collection_point_path %>
      </li>
    <% elsif current_user.role?("Donator") %>
      <li>
          <%= link_to icon('recycle', 'Nova Doação'), new_donation_path %>
      </li>
    <% end %> 
    <li>
      <%= link_to icon('times', 'Logout'), destroy_user_session_path,
        method: :delete %>
    </li>
  </ul>
</li>

app/views/layouts/_login.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= icon('caret-square-o-down', 'Login') %></a>
  <ul class="dropdown-menu" style="padding: 15px;min-width: 250px;">
    <li>
      <div class="row">
        <div class="col-md-12">
          <%= simple_form_for(:user, url: session_path(:user)) do |f| %>
          <%= f.input :email, label: false, placeholder: "Email" %>
          <%= f.input :password, autocomplete: "off", label: false, placeholder: "Password" %>
          <%= f.submit "Entrar", class: 'btn btn-success col-md-12' %>
          <% end %>
        </div>
      </div><!-- end row -->
    </li>
    <li>
      <div class="row" style="padding-top: 10px;">
        <div class="col-md-12">
          <%= link_to 'Cadastre-se', new_user_registration_path, class: 'btn btn-default col-md-12' %>
        </div>
      </div>
    </li>
    <li class="divider"></li>
    <li>
      <div class="row">
        <div class="col-md-12">
          <p class="text-small text-muted">Ou faça login com:</p>
          <div class="btn-group btn-group-lg btn-group-justified">
            <%= link_to user_omniauth_authorize_path(:facebook), class: "btn btn-primary btn-group-xs" do %>
            <%= icon('facebook-square') %>
            <% end %>  
            <%= link_to user_omniauth_authorize_path(:twitter), class: "btn btn-info btn-group-xs" do %>
            <%= icon('twitter-square') %>
            <% end %>
            <%= link_to root_path, class: "btn btn-danger btn-group-xs" do %>
            <%= icon('google-plus-square') %>
            <% end %>
            <%= link_to user_omniauth_authorize_path(:linkedin), class: "btn btn-primary btn-group-xs" do %>
            <%= icon('linkedin-square') %>
            <% end %>
          </div>
        </div>
      </div><!-- end row -->
    </li>
  </ul>
</li>

app/views/layouts/_messages.html.erb
<div class="container">
	<div class="row">
		<% flash.each do |name, msg| %>
		  <% if msg.is_a?(String) %>
	  		<div class="alert alert-<%= name == :notice ? "success" : "danger" %>"
	  			style="margin-top: 30px;">
		  		<a class="close" data-dismiss="alert">&#215;</a>
		  		<%= content_tag :div, msg, :id => "flash_#{name}" %>
	  		</div>
		  <% end %>
		<% end %>
	</div>
</div>

app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" 
        data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div style="margin-top: 10px; margin-right: 5px;"><%= image_tag "logo.png", size: '130x50', class: "img-responsive" %></div>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params[:controller] == 'welcome' %>">
          <%= link_to icon('home', 'Início'), root_path %>
        </li>
        <li class="<%= 'active' if params[:controller] == 'abouts' %>">
          <%= link_to icon('info', 'Nosso Trabalho'), abouts_path %>
        </li>
        <li class="<%= 'active' if params[:controller] == 'bonus' %>">
          <%= link_to icon('list-alt', 'Lista de Pontos'), bonus_path %>
        </li>
        <li class="<%= 'active' if params[:controller] == 'contacts' %>">
          <%= link_to icon('phone', 'Contato'), new_contact_path %>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <%= render 'layouts/logged_user' %>
        <% else %>
          <%= render 'layouts/login' %>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- container -->
</nav>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RECOL</title>

  <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    "application", "https://fonts.googleapis.com/css?family=Permanent+Marker", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>
	
	<%= render 'layouts/navbar' %>
	<%= render 'layouts/messages' %>
	<%= yield %>

	<div class="footer">
		<div class="container">
			<div class="row">
				<p class="foot">
					Copyright &copy; StartApps <%= Time.now.year %>
					<%= link_to icon('twitter-square'), root_path, class: 'pull-right' %>
					<%= link_to icon('facebook-square'), root_path, class: 'pull-right' %>
				</p>
			</div>
		</div>
	</div>

</body>
</html>